name: Build STM32 Firmware with mk-build-deps

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    
    runs-on: ubuntu-latest

    container:
      image: debian:bookworm
      options: --user root

    steps:
    - name: Install dependencies
      run: apt-get update; apt-get install -y  gcc-arm-none-eabi make git python3

    - name: Checkout Repositor with submodules 
      uses: actions/checkout@v4
      with:
          submodules: recursive
          
    - name: Build libopemcm3 libraries for stm32f4x
      run: make -C libopencm3 TARGETS=stm32/f4

    - name: Build product
      run: make -C src
