name: Build STM32 Firmware with mk-build-deps

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    container:
      image: debian:bookworm
      options: --user root

    steps:
    - name: Install dependencies
      run: apt-get update; apt-get install gcc-arm-none-eabi

    - name: Checkout Repositor with submodules 
      uses: actions/checkout@v4
      with:
          submodule: recursive

    - name: Build
      run: make -C src
